const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Camera3D,
		C3.Plugins.Audio,
		C3.Plugins.gamepad,
		C3.Plugins.Keyboard,
		C3.Plugins.LocalStorage,
		C3.Plugins.Sprite,
		C3.Behaviors.Timer,
		C3.Plugins.Arr,
		C3.Plugins.Shape3D,
		C3.Behaviors.Tween,
		C3.Behaviors.TileMovement,
		C3.Behaviors.Rotate,
		C3.Plugins.Tilemap,
		C3.Plugins.TiledBg,
		C3.Behaviors.Bullet,
		C3.Behaviors.Sin,
		C3.Plugins.Spritefont2,
		C3.Plugins.SVGPicture,
		C3.Behaviors.Flash,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Camera3D.Acts.SetFieldOfView,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.PickByEvaluate,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Tilemap.Acts.Destroy,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Tilemap.Exps.X,
		C3.Plugins.Tilemap.Exps.Y,
		C3.Plugins.TiledBg.Acts.SetSize,
		C3.Plugins.Tilemap.Exps.Width,
		C3.Plugins.Tilemap.Exps.Height,
		C3.Plugins.TiledBg.Acts.SetMeshSize,
		C3.Plugins.Tilemap.Exps.MapDisplayWidth,
		C3.Plugins.Tilemap.Exps.MapDisplayHeight,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Tilemap.Exps.TileAt,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.System.Cnds.EvaluateExpression,
		C3.Plugins.Tilemap.Exps.TileToPositionX,
		C3.Plugins.Tilemap.Exps.TileToPositionY,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Shape3D.Exps.UID,
		C3.Plugins.Shape3D.Acts.SetHeight,
		C3.Plugins.Shape3D.Exps.Height,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Shape3D.Exps.LayerName,
		C3.Plugins.Shape3D.Exps.X,
		C3.Plugins.Shape3D.Exps.Y,
		C3.Plugins.Shape3D.Acts.AddChild,
		C3.Plugins.Shape3D.Acts.SetFaceObject,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Shape3D.Cnds.PickByUID,
		C3.Plugins.Shape3D.Acts.SetVisible,
		C3.Plugins.Shape3D.Acts.SetInstanceVar,
		C3.Plugins.Shape3D.Exps.Width,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.System.Exps.random,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.Shape3D.Acts.SetSize,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Shape3D.Acts.SetZElevation,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Cnds.PickRandom,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.gamepad.Cnds.OnButtonDown,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.TiledBg.Acts.SetMeshPoint,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Shape3D.Acts.SetAngle,
		C3.Plugins.Camera3D.Exps.CameraX,
		C3.Plugins.Camera3D.Exps.CameraY,
		C3.Plugins.Camera3D.Exps.LookX,
		C3.Plugins.Camera3D.Exps.LookY,
		C3.Plugins.Camera3D.Acts.LookAtPosition,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Camera3D.Exps.CameraZ,
		C3.Plugins.Shape3D.Exps.ZElevation,
		C3.Plugins.Shape3D.Exps.ZHeight,
		C3.Plugins.Shape3D.Acts.SetEffectParam,
		C3.Plugins.Sprite.Cnds.IsOverlappingOffset,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Behaviors.Tween.Acts.StopTweens,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Shape3D.Acts.SetPos,
		C3.Plugins.Shape3D.Exps.Angle,
		C3.Behaviors.Timer.Acts.StopTimer,
		C3.Plugins.Shape3D.Acts.SetBoolInstanceVar,
		C3.Plugins.Shape3D.Cnds.PickChildren,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Camera3D.Exps.LayerToLayerX,
		C3.Plugins.Sprite.Exps.ZElevation,
		C3.Plugins.Sprite.Acts.SetZElevation,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Exps.ImageWidth,
		C3.Plugins.Sprite.Exps.ImageHeight,
		C3.Plugins.Shape3D.Cnds.IsOverlapping,
		C3.Plugins.Shape3D.Exps.Count,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.System.Exps.originalviewportheight,
		C3.Plugins.System.Exps.originalviewportwidth,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Behaviors.Bullet.Acts.SetGravity,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Exps.zeropad,
		C3.Plugins.SVGPicture.Acts.SetSize,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Spritefont2.Acts.TypewriterText,
		C3.Plugins.System.Exps.int,
		C3.Plugins.TiledBg.Exps.Width,
		C3.Plugins.TiledBg.Exps.Height,
		C3.Plugins.TiledBg.Exps.MeshRows,
		C3.Plugins.TiledBg.Exps.MeshColumns,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.LocalStorage.Acts.RemoveItem,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.System.Cnds.ForEachOrdered,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.Sprite.Exps.Width
	];
};
self.C3_JsPropNameTable = [
	{"3DCamera": 0},
	{Audio: 0},
	{Gamepad: 0},
	{Keyboard: 0},
	{LocalStorage: 0},
	{Timer: 0},
	{GameManager: 0},
	{WaterPoints: 0},
	{DefaultWidth: 0},
	{DefaultHeight: 0},
	{Luminosity: 0},
	{CrateShape: 0},
	{GoalShape: 0},
	{IsMoving: 0},
	{AngleOfMotion: 0},
	{Tween: 0},
	{TileMovement: 0},
	{PlayerCollision: 0},
	{PlayerShadow: 0},
	{PlayerShape: 0},
	{PlayerTexture: 0},
	{Rotate: 0},
	{StarShape: 0},
	{WallShape: 0},
	{Scared: 0},
	{BirdShape: 0},
	{BirdTexture: 0},
	{BushShape: 0},
	{GameplaySky: 0},
	{LevelIndex: 0},
	{Level: 0},
	{GrassShape: 0},
	{GrassTexture: 0},
	{FloorShape: 0},
	{OuterWallShape: 0},
	{RockShape: 0},
	{TreeShape: 0},
	{Water: 0},
	{Bullet: 0},
	{Confetto: 0},
	{ControlButton: 0},
	{ControlButtonBackground: 0},
	{ID: 0},
	{Sine: 0},
	{HUDIcon: 0},
	{KeyboardHint: 0},
	{DepthOfFieldMask: 0},
	{Fade: 0},
	{ReferenceGrid: 0},
	{SpriteFontGradient: 0},
	{SpriteFontWhite: 0},
	{TransitionHandMask: 0},
	{TutorialModal: 0},
	{TutorialSign: 0},
	{DancingPlayer: 0},
	{Index: 0},
	{IsFull: 0},
	{Gem: 0},
	{GemFrameBackground: 0},
	{GemFrameBorder: 0},
	{GrassField: 0},
	{OpeningCamera: 0},
	{Title: 0},
	{TitleScreenSky: 0},
	{CreditsHolder: 0},
	{CreditsRoomShape: 0},
	{Shape: 0},
	{Billboard: 0},
	{Flash: 0},
	{Text: 0},
	{SelectedLevelIndex: 0},
	{CurrentTile: 0},
	{CurrentTileX: 0},
	{CurrentTileY: 0},
	{UID: 0},
	{PositionX: 0},
	{PositionY: 0},
	{DISTORTIONSPEED: 0},
	{DISTORTIONSTRENGTH: 0},
	{CameraScale: 0},
	{Scale: 0},
	{Interpolate: 0},
	{CrateUID: 0},
	{Steps: 0},
	{ANIMATIONDURATION: 0},
	{MovePlayer: 0},
	{MoveCrate: 0},
	{IsOverlappingWallOneCellAway: 0},
	{IsOverlappingWallTwoCellsAway: 0},
	{IsOverlappingCrateOneCellAway: 0},
	{IsOverlappingCrateTwoCellsAway: 0},
	{AnimationName: 0},
	{UseAngleOfMotion: 0},
	{CorrectCrates: 0},
	{RandomScale: 0},
	{HUDIconID: 0},
	{FADEDURATION: 0},
	{IsBusy: 0},
	{NextLayoutNameBuffer: 0},
	{NextInputFocusBuffer: 0},
	{NextLayoutName: 0},
	{NextInputFocus: 0},
	{DisplayTutorial: 0},
	{InputFocus: 0},
	{LASTLEVELINDEX: 0},
	{CompletedLevels: 0},
	{SFXName: 0},
	{Volume: 0},
	{TypewriterDuration: 0},
	{A: 0},
	{B: 0},
	{C: 0},
	{RandomMin: 0},
	{RandomMax: 0},
	{Number: 0},
	{Multiple: 0},
	{HeightMultiplier: 0},
	{AnimationNormalizedProgress: 0},
	{ErasureProgress: 0},
	{ErasePlayerProfile: 0},
	{GemMin: 0},
	{GemMax: 0},
	{NormalizedProgress: 0},
	{ROOMDEPTH: 0},
	{COMEANDGOTIME: 0},
	{STAYTIME: 0},
	{Name: 0},
	{Role: 0}
];

self.InstanceType = {
	_3DCamera: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Gamepad: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	GameManager: class extends self.ISpriteInstance {},
	WaterPoints: class extends self.IArrayInstance {},
	CrateShape: class extends self.I3DShapeInstance {},
	GoalShape: class extends self.I3DShapeInstance {},
	PlayerCollision: class extends self.ISpriteInstance {},
	PlayerShadow: class extends self.ISpriteInstance {},
	PlayerShape: class extends self.I3DShapeInstance {},
	PlayerTexture: class extends self.ISpriteInstance {},
	StarShape: class extends self.I3DShapeInstance {},
	WallShape: class extends self.I3DShapeInstance {},
	BirdShape: class extends self.I3DShapeInstance {},
	BirdTexture: class extends self.ISpriteInstance {},
	BushShape: class extends self.I3DShapeInstance {},
	GameplaySky: class extends self.ISpriteInstance {},
	Level: class extends self.ITilemapInstance {},
	GrassShape: class extends self.I3DShapeInstance {},
	GrassTexture: class extends self.ISpriteInstance {},
	FloorShape: class extends self.I3DShapeInstance {},
	OuterWallShape: class extends self.I3DShapeInstance {},
	RockShape: class extends self.I3DShapeInstance {},
	TreeShape: class extends self.I3DShapeInstance {},
	Water: class extends self.ITiledBackgroundInstance {},
	Confetto: class extends self.ISpriteInstance {},
	ControlButton: class extends self.ISpriteInstance {},
	ControlButtonBackground: class extends self.ISpriteInstance {},
	HUDIcon: class extends self.ISpriteInstance {},
	KeyboardHint: class extends self.ISpriteInstance {},
	DepthOfFieldMask: class extends self.ITiledBackgroundInstance {},
	Fade: class extends self.ITiledBackgroundInstance {},
	ReferenceGrid: class extends self.ITiledBackgroundInstance {},
	SpriteFontGradient: class extends self.ISpriteFontInstance {},
	SpriteFontWhite: class extends self.ISpriteFontInstance {},
	TransitionHandMask: class extends self.ISVGPictureInstance {},
	TutorialModal: class extends self.ITiledBackgroundInstance {},
	TutorialSign: class extends self.ISpriteInstance {},
	DancingPlayer: class extends self.I3DShapeInstance {},
	Gem: class extends self.ISpriteInstance {},
	GemFrameBackground: class extends self.ISpriteInstance {},
	GemFrameBorder: class extends self.ISpriteInstance {},
	GrassField: class extends self.ITiledBackgroundInstance {},
	OpeningCamera: class extends self.ISpriteInstance {},
	Title: class extends self.I3DShapeInstance {},
	TitleScreenSky: class extends self.ISpriteInstance {},
	CreditsHolder: class extends self.ISpriteInstance {},
	CreditsRoomShape: class extends self.I3DShapeInstance {},
	Shape: class extends self.I3DShapeInstance {},
	Billboard: class extends self.I3DShapeInstance {},
	Text: class extends self.ISpriteFontInstance {}
}